Import relevant Libraries

In [1]:
import numpy as np

Scalar

In [2]:
s = 5
s

5

Vectors

In [3]:
v = np.array([5,2,-4])

In [4]:
v

array([ 5,  2, -4])

Matrices

In [5]:
matrix = np.array([[5,2,12],[3,-4,3]])

In [6]:
matrix

array([[ 5,  2, 12],
       [ 3, -4,  3]])

In [7]:
type(matrix)

numpy.ndarray

In [8]:
type(v)

numpy.ndarray

In [9]:
matrix.shape

(2, 3)

In [10]:
v.shape

(3,)

In [11]:
v.reshape(1,3)

array([[ 5,  2, -4]])

In [12]:
v.reshape(3,1)

array([[ 5],
       [ 2],
       [-4]])

In [13]:
v

array([ 5,  2, -4])

Tensor 
 - Generalization of all the cases above
 - Scalar -> Rank 0
 - Vector -> Rank 1
 - Matrix -> Rank 2

In [14]:
m1 = np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
m2 = np.array([[7,8,9],[10,11,12]])
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
t = np.array([m1,m2])
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
t.shape

(2, 2, 3)

In [18]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [20]:
m1+m2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [21]:
m1-m2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [22]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
m1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
m1 = np.array([1,2,3]) 

In [26]:
m1

array([1, 2, 3])

In [27]:
m2 = np.array([4,5,6])

In [28]:
np.dot(m1,m2)

np.int64(32)

In [29]:
print(np.dot(m1,m2))

32


In [30]:
A = np.array([[1,2,3],[4,5,6]])

In [31]:
B = np.array([[1,0,0],[0,1,0],[0,0,1]])
B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
B.shape

(3, 3)

In [33]:
A.shape

(2, 3)

In [34]:
np.dot(A,B)

array([[1, 2, 3],
       [4, 5, 6]])

# Linear Algebra
- Vectorized Code
- Image Recognition
- Dimensionality Reduction