## Importing Data with NumPy

In [ ]:
import numpy as np

### np.loadtxt() vs np.genfromtxt()

In [ ]:
lending_co_data_numeric_1 = np.loadtxt('Lending-Company-Numeric-Data.csv', delimiter=',')
lending_co_data_numeric_1

In [ ]:
lending_co_data_numeric_2 = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter=',')
lending_co_data_numeric_2

In [ ]:
np.array_equal(lending_co_data_numeric_1, lending_co_data_numeric_2)

In [ ]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=';')
lending_co_data_numeric_NAN

In [ ]:
lending_co_data_numeric_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=';', dtype=np.str_)
lending_co_data_numeric_NAN

### Partial Cleaning While Importing

In [1]:
import numpy as np

In [2]:
lending_co_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter=';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [3]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';', skip_header=2)
lending_co_data_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1041, 6))

In [4]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';', usecols=(0,1,5))
lending_co_data_numeric_NAN

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]], shape=(1043, 3))

In [6]:
lending_1, lending_2, lending_3 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv', delimiter=';', skip_header=2, usecols=(0,1,5), unpack=True)
print(lending_1)
print(lending_2)
print(lending_3)


[1000. 2000. 2000. ...   nan 1000. 2000.]
[40. 40. 50. ... 40. 40. 40.]
[15340. 15321. 13720. ... 16600. 15600. 16600.]


### String vs Object vs Numbers